name: flutter_social_share_example
description: Demonstrates how to use the flutter_social_share plugin.
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_social_share:
    path: ../
  cupertino_icons: ^1.0.3
  path_provider: ^2.0.5
  permission_handler: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/